### ISSUE TITLE
Table of contents issue

### ISSUE THREAD

**Issue by VelNZ** [VelNZ/mastersdoctoralthesislatex#15]
From: http://latex-community.org/forum/viewtopic.php?f=59&t=26892&p=92498

Tested and affects v2.1 currently on LaTeXTemplates.com.

@johannesbottcher could you have a look at this?

**Comment by johannesbottcher** [comment]
Busy right now, this should be the `\phantomsection` issue reported earlier. I'll have a look later.

**Comment by johannesbottcher** [comment]
this is indeed the `\phantomsection` i missed earlier. This is already fixed for 2.2

**Comment by VelNZ** [comment]
Excellent, thanks for checking it out!
