### ISSUE TITLE
llicense of the class file

### ISSUE THREAD

**Issue by johannesbottcher** [VelNZ/mastersdoctoralthesislatex#6]
Since a user does not have the direct need to edit the class file, i think it  would be better to put it under a litle bit more restrictive license. The LPPL 1.3 or higher is the license most package and class authors choose. It allows use, redistribution and changes, but changes only, if the file name is changed. 

That would be a great way for helpers (including me) to immediately see if something fishy might have happened and finally stops the fault Sunil introduced a few years back. I summed up the [history and evolution of this template](https://github.com/johannesbottcher/templateConfusion/blob/master/ourFamousThesisTemplate.md).

**Comment by johannesbottcher** [comment]
http://ctan.org/pkg/modguide

What is presented in that article should be valid for the class `MastersDoctoralThesis.cls` as well. Else, supporting the class will be a nightmare, just as it was (and still is) for `Thesis.cls`.

**Comment by VelNZ** [comment]
Ok what do you think of this: https://github.com/VelNZ/mastersdoctoralthesislatex/commit/3c8558643f5f3ba326d261131d65484eff06baca

**Comment by johannesbottcher** [comment]
I am ok with almost everything but one line 

```syntax=latex
\ProvidesClass{\classname}[08/11/15] v1.2 LaTeX document class]
```

My editor does syntax highlighting so i immediately were able to spot that something is fishy. The line should be 

```syntax=latex
\ProvidesClass{\classname}[2015/11/08  v1.2 LaTeX document class]
```
to follow rules of LaTeX's date format. Of course, the extra bracket had to be removed as well. 

The rest looks good, though. Thanks :-)

PS: maybe you want to change the string `LaTeX document class`  to something else, for example `latex-templates.com`. This will appear in every log file the class is involved, which gives your site a bit more traffic when a question needs support and is a help for supporters as well. ;-)

**Comment by VelNZ** [comment]
Thanks! Accidentally added that bracket and didn't know the date had to be formatted that way. Great tip about adding the URL in too :)

https://github.com/VelNZ/mastersdoctoralthesislatex/commit/e1f5f4b270056ee031975827cedfd3f92dd28c74
