### ISSUE TITLE
addchap 

### ISSUE THREAD

**Issue by johannesbottcher** [VelNZ/mastersdoctoralthesislatex#7]
In the latest commit on master, the `\addchap` command fell back to an older version, which wasn't supposed to happen. Can you revert the changes?

**Comment by VelNZ** [comment]
I think I fixed this, can you please confirm it?

https://github.com/VelNZ/mastersdoctoralthesislatex/commit/2e1db055c00497728fc1a452f849afe075549c2d

Note that I think you had the wrong argument before, you had \MakeMarkCase{#3} in the #2 block. Check it all over and let me know if it's still wrong.

**Comment by johannesbottcher** [comment]
Thanks for spotting this, the whole block should be ok now.
